# List of Ad-/Malware filter lists to use in AdGuardHome

{
    services.adguardhome.settings.filters = [
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt";
            name = "AdGuard DNS filter";
            id = 1; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt";
            name = "AdAway Default Blocklist";
            id = 2; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt";
            name = "1Hosts (Lite)";
            id = 3; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_38.txt";
            name = "1Hosts (mini)";
            id = 4; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt";
            name = "Dan Pollock's List";
            id = 5; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt";
            name = "HaGeZi Personal Black & White";
            id = 6; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt";
            name = "The NoTracking blocklist";
            id = 7; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_5.txt";
            name = "OISD Blocklist Basic";
            id = 8; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt";
            name = "OISD Blocklist Full";
            id = 9; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt";
            name = "Peter Lowe's Blocklist";
            id = 10; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt";
            name = "Steven Black's List";
            id = 11; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt";
            name = "Dandelion Sprout's Game Console Adblock List";
            id = 12; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt";
            name = "Perflyst and Dandelion Sprout's Smart-TV Blocklist";
            id = 13; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt";
            name = "WindowsSpyBlocker - Hosts spy rules";
            id = 14; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt";
            name = "Phishing URL Blocklist (PhishTank and OpenPhish)";
            id = 15; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt";
            name = "Dandelion Sprout's Anti-Malware List";
            id = 16; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt";
            name = "NoCoin Filter List";
            id = 17; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt";
            name = "Scam Blocklist by DurableNapkin";
            id = 18; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt";
            name = "Stalkerware Indicators List";
            id = 19; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt";
            name = "Malicious URL Blocklist (URLHaus)";
            id = 20; }
        {   enabled = true;
            url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt";
            name = "The Big List of Hacked Malware Web Sites";
            id = 21; }
    ];
}
